# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PackagerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QStandardItem
from PyQt5.QtCore import *
from src.Packager import Packager
import os


class PackagerWidget(QWidget):

    def __init__(self, project=None):
        super().__init__()
        self.setWindowTitle("Packager")
        self.packager = Packager()
        
        self.UI()
        self.resize(1000,500)
        self.show()

    def UI(self):
        self.gridLayout = QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")

        # Project layout
        self.projectLayout = QHBoxLayout()
        self.projectLayout.setObjectName("projectLayout")


        #Package Items Table
        self.vmTable = QTableWidget(0, 3, self)
        self.vmTable.setEditTriggers(QAbstractItemView.NoEditTriggers) 

        # Creating headers for columns in table
        type_header = QTableWidgetItem('Item Type')
        self.vmTable.setHorizontalHeaderItem(0, type_header)
        descriptionHeader = QTableWidgetItem('Name')
        self.vmTable.setHorizontalHeaderItem(1, descriptionHeader)

        includeHeader = QTableWidgetItem('Include')
        self.vmTable.setHorizontalHeaderItem(2, includeHeader)

        self.vmTable.horizontalHeader().setStretchLastSection(False)
        self.vmTable.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.vmTable.horizontalHeader().setSectionResizeMode(0,QHeaderView.ResizeToContents)
        self.vmTable.horizontalHeader().setSectionResizeMode(2,QHeaderView.ResizeToContents)

        self.populate_table()

        self.projectLayout.addWidget(self.vmTable)

        # Project-related buttons
        self.projectVerticalLayout = QtWidgets.QVBoxLayout()
        self.projectVerticalLayout.setObjectName("projectVerticalLayout")

        self.packageProjectButton = QtWidgets.QPushButton()
        self.packageProjectButton.setObjectName("packageProjectButton")
        self.packageProjectButton.clicked.connect(self.package_files)

        self.importFilesButton = QtWidgets.QPushButton()
        self.importFilesButton.setObjectName("importFilesButton")
        self.importFilesButton.clicked.connect(self.add_file)

        self.importProjectButton = QtWidgets.QPushButton()
        self.importProjectButton.setObjectName("importProjectButton")
        self.importProjectButton.clicked.connect(self.import_project)

        self.projectVerticalLayout.addWidget(self.packageProjectButton)
        self.projectVerticalLayout.addWidget(self.importFilesButton)
        self.projectVerticalLayout.addWidget(self.importProjectButton)
        
        self.projectLayout.addLayout(self.projectVerticalLayout)

        self.gridLayout.addLayout(self.projectLayout, 0, 0)

        self.setLayout(self.gridLayout)
        self.retranslateUi()
    def populate_table(self):
        vm_list = self.packager.get_vm_list()
        i=0
        self.vmTable.setRowCount(len(vm_list))
        for vm in vm_list:
            checkbox = QCheckBox()
            self.vmTable.setItem(i,0,QTableWidgetItem("VM"))
            self.vmTable.setItem(i,1,QTableWidgetItem(vm))
            self.vmTable.setCellWidget(i,2, checkbox)
            i=i+1

    def add_file(self):
        file_list = QtWidgets.QFileDialog.getOpenFileNames(parent=self, caption="Select File", directory=os.path.realpath(os.getcwd()))
        for item in file_list[0]:
            self.vmTable.setRowCount(self.vmTable.rowCount()+1)
            current_row_pos = self.vmTable.rowCount()-1

            self.vmTable.setItem(current_row_pos, 0, QTableWidgetItem("File"))
            self.vmTable.setItem(current_row_pos, 1, QTableWidgetItem(item))

            deleteButton = QPushButton('Delete')
            deleteButton.clicked.connect(self.deleteRow)
            self.vmTable.setCellWidget(current_row_pos, 2, deleteButton)

    def deleteRow(self):
        button = self.sender()
        if button:
            row = self.vmTable.indexAt(button.pos()).row()
            self.vmTable.removeRow(row)
    
    def package_files(self):
        output_zip = QtWidgets.QFileDialog.getSaveFileName(parent=self, caption="Save Zip File", directory=os.path.realpath(os.getcwd()), filter="Zip (*.zip)")
        print(output_zip)
        selectedVms = []
        includedFiles = [] 
        i=0
        while i < self.vmTable.rowCount():
            fileTypeTemp = self.vmTable.item(i,0) #This should be our files type
            file_type =fileTypeTemp.text()

            filePathTemp = self.vmTable.item(i,1)#This should be our files path or VM Name
            file_path =filePathTemp.text()

            if file_type == "File":
                includedFiles.append(file_path)
            if file_type == "VM":
                checkbox = self.vmTable.cellWidget(i,2)
                if checkbox.isChecked():
                    selectedVms.append(file_path)
            i = i+1
        if output_zip[0] != '':
            self.progressbar = ProgressBar()
            self.progressbar.show()
            self.packager.export_to_zip(vm_list=selectedVms, file_list = includedFiles, output_file = output_zip[0])
            self.progressbar.close()
            QMessageBox.information(self, "Success", "Project ZIP has been created.")
        else:
            QMessageBox.critical(self, "Failure", "No File selected.")

    def import_project(self):
        input_zip = QtWidgets.QFileDialog.getOpenFileName(parent=self, caption="Select Zip File", directory=os.path.realpath(os.getcwd()), filter="Zip (*.zip)")
        if input_zip[0] != '':
            self.progressbar = ProgressBar()
            self.progressbar.show()
            self.packager.import_from_zip(zip_file=input_zip[0])
            self.progressbar.close()

            self.vmTable.clearContents()
            self.vmTable.model().removeRows(0, self.vmTable.rowCount())
            self.populate_table()

            QMessageBox.information(self, "Success", "VIrtual Machines imported to VirtualBox. Extra files have been copied to new folder in zip file directory.")
        else:
            QMessageBox.critical(self, "Failure", "No File selected.")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("PackagerTab", "Packager"))
        

        self.packageProjectButton.setText(_translate("Widget", "Package Project..."))
        self.importFilesButton.setText(_translate("Widget", "Add Files to Project..."))
        self.importProjectButton.setText(_translate("Widget", "Import Packaged Project..."))

class ProgressBar(QWidget):

    def __init__(self):
        super().__init__()
        self.pbar = QProgressBar(self)
        self.pbar.setGeometry(30, 40, 500, 75)
        self.pbar.setRange(0,0)
        self.layout = QVBoxLayout()
        self.layout.addWidget(self.pbar)
        self.setLayout(self.layout)
        self.setGeometry(300, 300, 550, 100)
        self.move(QApplication.desktop().screen().rect().center()- self.rect().center())
        self.setWindowTitle('Progress Bar')

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    #setup style sheet
    style = """
        QPushButton{
            color: #ffffff;
            background: #8f8f8f;
            border: 3px #000000 solid;
            padding: 5px 10px;
            border-radius: 2px;
            font-weight: plain;
            font-size: 9pt;
            outline: none;
        }
        QPushButton:hover{
            border: 3px #000000 solid;
            background: #80aaff;
        }
    """
    app.setStyleSheet(style)
    # # # # #end style
    ui = PackagerWidget()
    ui.show()
    sys.exit(app.exec_())