# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Packager.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(492, 393)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VMList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.VMList.setLineWidth(1)
        self.VMList.setMidLineWidth(0)
        self.VMList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.VMList.setGridSize(QtCore.QSize(1, 10))
        self.VMList.setViewMode(QtWidgets.QListView.ListMode)
        self.VMList.setModelColumn(0)
        self.VMList.setUniformItemSizes(True)
        self.VMList.setWordWrap(False)
        self.VMList.setObjectName("VMList")
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        self.horizontalLayout.addWidget(self.VMList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 290, 491, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.VMList.setSortingEnabled(False)
        __sortingEnabled = self.VMList.isSortingEnabled()
        self.VMList.setSortingEnabled(False)
        item = self.VMList.item(0)
        item.setText(_translate("Widget", "VM1 (Main) Testing Agent: Kali Linux"))
        item = self.VMList.item(1)
        item.setText(_translate("Widget", "VM2 Web Server: Kali Linux"))
        item = self.VMList.item(2)
        item.setText(_translate("Widget", "VM3 Web Client: Kali Linux"))
        self.VMList.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("Widget", "Package VMs..."))
        self.pushButton_3.setText(_translate("Widget", "Import VM to Project..."))
        self.pushButton.setText(_translate("Widget", "Delete VM..."))
        self.pushButton_4.setText(_translate("Widget", "Open Project..."))
        self.pushButton_5.setText(_translate("Widget", "New Project"))
        self.pushButton_6.setText(_translate("Widget", "Launch Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
