# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        Widget.setMinimumSize(QtCore.QSize(640, 480))
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_label = QtWidgets.QLabel(Widget)
        self.project_label.setObjectName("project_label")
        self.verticalLayout.addWidget(self.project_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.project_info = QtWidgets.QListWidget(Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_info.sizePolicy().hasHeightForWidth())
        self.project_info.setSizePolicy(sizePolicy)
        self.project_info.setMinimumSize(QtCore.QSize(0, 0))
        self.project_info.setObjectName("project_info")
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.project_info.addItem(item)
        self.verticalLayout.addWidget(self.project_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_button = QtWidgets.QPushButton(Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setDefault(False)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button, 0, QtCore.Qt.AlignLeft)
        self.runner_button = QtWidgets.QPushButton(Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runner_button.sizePolicy().hasHeightForWidth())
        self.runner_button.setSizePolicy(sizePolicy)
        self.runner_button.setObjectName("runner_button")
        self.horizontalLayout.addWidget(self.runner_button, 0, QtCore.Qt.AlignHCenter)
        self.launch_builder = QtWidgets.QPushButton(Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launch_builder.sizePolicy().hasHeightForWidth())
        self.launch_builder.setSizePolicy(sizePolicy)
        self.launch_builder.setDefault(False)
        self.launch_builder.setObjectName("launch_builder")
        self.horizontalLayout.addWidget(self.launch_builder, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.project_label.setText(_translate("Widget", "Project Details"))
        __sortingEnabled = self.project_info.isSortingEnabled()
        self.project_info.setSortingEnabled(False)
        item = self.project_info.item(0)
        item.setText(_translate("Widget", "Salient Artifacts: 6"))
        item = self.project_info.item(1)
        item.setText(_translate("Widget", "Dependencies: 10"))
        item = self.project_info.item(2)
        item.setText(_translate("Widget", "Root Directory: /user/abs/x/proj1"))
        item = self.project_info.item(3)
        item.setText(_translate("Widget", "Imported Data Directory: /user/eceld/x/recording1"))
        item = self.project_info.item(4)
        item.setText(_translate("Widget", "Salient Artifact Directory: /user/abs/x/proj1/salientartifacts.txt"))
        self.project_info.setSortingEnabled(__sortingEnabled)
        self.close_button.setText(_translate("Widget", "Close Project"))
        self.runner_button.setText(_translate("Widget", "Launch Runner"))
        self.launch_builder.setText(_translate("Widget", "Launch Builder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
