# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QStandardItem
from PyQt5.QtCore import *

class LauncherWidget(QWidget):

    def __init__(self):
        super().__init__()
        self.UI()
        self.show()

    def UI(self):
        self.setObjectName("launcher_widget")

        # Window sizing
        self.resize(320, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(320, 240))

        # ABS Logo
        self.label = QtWidgets.QLabel(self)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Resources/Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        # Button to create new project
        self.new_button = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_button.sizePolicy().hasHeightForWidth())
        self.new_button.setSizePolicy(sizePolicy)
        self.new_button.setDefault(False)
        self.new_button.setObjectName("new_button")

        # Button to open existing project
        self.open_button = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setObjectName("open_button")

        # Layout that structures buttons
        self.button_layout = QtWidgets.QGridLayout()
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.button_layout.setContentsMargins(-1, -1, -1, 0)
        self.button_layout.setSpacing(0)
        self.button_layout.setObjectName("button_layout")
        self.button_layout.addWidget(self.new_button, 0, 1, 1, 1)
        self.button_layout.addWidget(self.open_button, 0, 0, 1, 1)

        # Widget layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Widget", "ABS - Launcher"))
        self.new_button.setText(_translate("Widget", "New Project..."))
        self.open_button.setText(_translate("Widget", "Open Project..."))

    def openProject(self):
        #(TODO): use python file browser to load the project
        
        self.file_browser = QFileDialog()
        self.file_browser.setFileMode(QFileDialog.ExistingFile)
        dlg.setFilter("JSON Files (*.json)")

        filename = QStringList()

        if self.file_browser.exec_():
            filename = self.file_browser.selectedFiiles()

            with open(filename[0], 'r') as f:
                #(TODO): read project from file
                #(TODO): send it to create widget
                print("debug")
                
    def newProject(self):
        self.creator = CreateWidget()
        self.creator.show()
        self.hide()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = LauncherWidget()
    ui.show()
    sys.exit(app.exec_())
