# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Packager.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys #new imports

from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QStandardItem
from PyQt5.QtCore import *

from PopupWidget import PopupWidget


class PackageWidget(QWidget):

    def __init__(self, previous_window=None):
        super().__init__()
        self.previous_window = previous_window
        self.UI()
        self.show()

    def UI(self):
        self.setObjectName("new_packager_widget")

        # Window sizing
        self.resize(300, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(300, 240))


        # Button to select VM
        self.select_vm_button = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_vm_button.sizePolicy().hasHeightForWidth())
        self.select_vm_button.setSizePolicy(sizePolicy)
        self.select_vm_button.setDefault(False)
        self.select_vm_button.setObjectName("select_vm_button")
        self.select_vm_button.clicked.connect(self.selectVm)

        # Button to select files
        self.select_files_button = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_files_button.sizePolicy().hasHeightForWidth())
        self.select_files_button.setSizePolicy(sizePolicy)
        self.select_files_button.setObjectName("select_files_button")
        self.select_files_button.clicked.connect(self.selectFiles)

        # Layout that structures buttons
        self.button_layout = QtWidgets.QGridLayout()
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.button_layout.setContentsMargins(-1, -1, -1, -1)
        self.button_layout.setSpacing(0)
        self.button_layout.setObjectName("button_layout")
        self.button_layout.addWidget(self.select_vm_button, 0, 1, 1, 1)
        self.button_layout.addWidget(self.select_files_button, 0, 0, 1, 1)

        # Widget layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Widget", "Packager"))
        self.select_vm_button.setText(_translate("Widget", " Select VM "))
        self.select_files_button.setText(_translate("Widget", "Select Files"))
        self.setWindowIcon(QtGui.QIcon("A.png"))# A icon

    def selectFiles(self):
        project_file = QFileDialog.getOpenFileName(self, 'Select Files')

                     
    def selectVm(self):
        project_file = QFileDialog.getOpenFileName(self, 'Select VM')


if __name__ == "__main__":
    #simport sys
    app = QtWidgets.QApplication(sys.argv)
    
    #setup style sheet
    style = """
        QPushButton{
            color: #ffffff;
            background: #8f8f8f;
            border: 3px #000000 solid;
            padding: 5px 10px;
            border-radius: 2px;
            font-weight: plain;
            font-size: 9pt;
            outline: none;
        }
        QPushButton:hover{
            border: 3px #000000 solid;
            background: #80aaff;
        }
    """
    app.setStyleSheet(style)
    # # # # #end style
    ui = PackageWidget()
    ui.show()
    sys.exit(app.exec_())