# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PackagerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QStandardItem
from PyQt5.QtCore import *


class PackagerWidget(QWidget):

    def __init__(self):
        super().__init__()
        self.setWindowTitle("Packager")
        self.UI()
        self.show()

    def UI(self):
        self.gridLayout = QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")

        # Project layout
        self.projectLayout = QHBoxLayout()
        self.projectLayout.setObjectName("projectLayout")

        # List of project files
        self.VMList = QtWidgets.QListWidget()
        self.VMList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.VMList.setViewMode(QtWidgets.QListView.ListMode)
        self.VMList.setUniformItemSizes(True)
        self.VMList.setWordWrap(True)
        self.VMList.setObjectName("VMList")

        # Sample VMs - These will be read from project files
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)

        # Project-related buttons
        self.projectVerticalLayout = QtWidgets.QVBoxLayout()
        self.projectVerticalLayout.setObjectName("projectVerticalLayout")

        self.packageProjectButton = QtWidgets.QPushButton()
        self.packageProjectButton.setObjectName("packageProjectButton")

        self.importVMButton = QtWidgets.QPushButton()
        self.importVMButton.setObjectName("importVMButton")

        self.importFilesButton = QtWidgets.QPushButton()
        self.importFilesButton.setObjectName("importFilesButton")

        self.deleteFilesButton = QtWidgets.QPushButton()
        self.deleteFilesButton.setObjectName("deleteFilesButton")

        self.projectVerticalLayout.addWidget(self.packageProjectButton)
        self.projectVerticalLayout.addWidget(self.importVMButton)
        self.projectVerticalLayout.addWidget(self.importFilesButton)
        self.projectVerticalLayout.addWidget(self.deleteFilesButton)
        
        self.projectLayout.addWidget(self.VMList)
        self.projectLayout.addLayout(self.projectVerticalLayout)

        # Packager button layout
        self.packagerLayout = QHBoxLayout()
        self.packagerLayout.setObjectName("packagerLayout")
        self.packagerLayout.setContentsMargins(30, 0, 30, 0)

        # Packager action buttons
        self.openProjectButton = QtWidgets.QPushButton()
        self.openProjectButton.setObjectName("openProjectButton")
        
        self.newProjectButton = QtWidgets.QPushButton()
        self.newProjectButton.setObjectName("newProjectButton")

        self.launchProjectButton = QtWidgets.QPushButton()
        self.launchProjectButton.setObjectName("launchProjectButton")

        spacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

        self.packagerLayout.addWidget(self.openProjectButton)
        self.packagerLayout.addWidget(self.newProjectButton)
        self.packagerLayout.addItem(spacer)
        self.packagerLayout.addWidget(self.launchProjectButton)

        self.gridLayout.addLayout(self.projectLayout, 0, 0)
        self.gridLayout.addLayout(self.packagerLayout, 1, 0)

        self.setLayout(self.gridLayout)
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("PackagerTab", "Packager"))

        # This might need to be done programatically instead of hardcoded
        item = self.VMList.item(0)
        item.setText(_translate("Widget", "Project root:\t\t/usr/x/abs/p1/"))
        item = self.VMList.item(1)
        item.setText(_translate("Widget", "VM 2:\t\t/usr/x/abs/p1/webserver_kali.ova"))
        item = self.VMList.item(2)
        item.setText(_translate("Widget", "VM 3:\t\t/usr/x/abs/p1/webclient_kali.ova"))
        item = self.VMList.item(3)
        item.setText(_translate("Widget", "VM 1:\t\t/usr/x/abs/p1/test_kali.ova"))
        

        self.packageProjectButton.setText(_translate("Widget", "Package Project..."))
        self.importVMButton.setText(_translate("Widget", "Import VM to Project..."))
        self.importFilesButton.setText(_translate("Widget", "Import Files to Project..."))
        self.deleteFilesButton.setText(_translate("Widget", "Delete Project Files..."))
        self.openProjectButton.setText(_translate("Widget", "Open Project..."))
        self.newProjectButton.setText(_translate("Widget", "New Project..."))
        self.launchProjectButton.setText(_translate("Widget", "Launch Project"))
