# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PackagerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PackagerTab(object):
    def setupUi(self, PackagerTab):
        PackagerTab.setObjectName("PackagerTab")
        PackagerTab.resize(496, 423)
        self.Packager = QtWidgets.QWidget()
        self.Packager.setObjectName("Packager")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Packager)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VMList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.VMList.setLineWidth(1)
        self.VMList.setMidLineWidth(0)
        self.VMList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.VMList.setGridSize(QtCore.QSize(1, 10))
        self.VMList.setViewMode(QtWidgets.QListView.ListMode)
        self.VMList.setModelColumn(0)
        self.VMList.setUniformItemSizes(True)
        self.VMList.setWordWrap(False)
        self.VMList.setObjectName("VMList")
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.VMList.addItem(item)
        self.horizontalLayout.addWidget(self.VMList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Packager)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 290, 514, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        PackagerTab.addTab(self.Packager, "")

        self.retranslateUi(PackagerTab)
        PackagerTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PackagerTab)

    def retranslateUi(self, PackagerTab):
        _translate = QtCore.QCoreApplication.translate
        PackagerTab.setWindowTitle(_translate("PackagerTab", "Packager"))
        self.VMList.setSortingEnabled(False)
        __sortingEnabled = self.VMList.isSortingEnabled()
        self.VMList.setSortingEnabled(False)
        item = self.VMList.item(0)
        item.setText(_translate("PackagerTab", "VM1 (Main) Testing Agent: Kali Linux"))
        item = self.VMList.item(1)
        item.setText(_translate("PackagerTab", "VM2 Web Server: Kali Linux"))
        item = self.VMList.item(2)
        item.setText(_translate("PackagerTab", "VM3 Web Client: Kali Linux"))
        self.VMList.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("PackagerTab", "Package VMs..."))
        self.pushButton_3.setText(_translate("PackagerTab", "Import VM to Project..."))
        self.pushButton.setText(_translate("PackagerTab", "Delete VM..."))
        self.pushButton_4.setText(_translate("PackagerTab", "Open Project..."))
        self.pushButton_5.setText(_translate("PackagerTab", "New Project"))
        self.pushButton_6.setText(_translate("PackagerTab", "Launch Project"))
        PackagerTab.setTabText(PackagerTab.indexOf(self.Packager), _translate("PackagerTab", "Packager"))
