# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QStandardItem
from PyQt5.QtCore import *


class PopupWidget(QWidget):
    def __init__(self, previous_window=None):
        super().__init__()
        self.previous_window = previous_window
        self.UI()
        self.show()

    def UI(self):
        self.setObjectName("popup_widget")
        self.resize(320, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(320, 240))

        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")

        self.popup_text = QtWidgets.QLabel(self)
        self.popup_text.setAlignment(QtCore.Qt.AlignCenter)
        self.popup_text.setObjectName("popup_text")
        self.popup_text.setWordWrap(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.popup_text.sizePolicy().hasHeightForWidth())
        self.popup_text.setSizePolicy(sizePolicy)

        self.continue_button = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_button.sizePolicy().hasHeightForWidth())
        self.continue_button.setSizePolicy(sizePolicy)
        self.continue_button.setObjectName("continue_button")
        self.continue_button.clicked.connect(self.closeRoutine)

        self.verticalLayout.addWidget(self.popup_text, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.continue_button, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, popup_title = "PLACEHOLDER TEXT _ REPLACE THIS", popup_text = "PLACEHOLDER TEXT _ REPLACE THIS"):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Widget", popup_title))
        self.popup_text.setText(_translate("Widget", popup_text))
        self.continue_button.setText(_translate("Widget", "Continue"))
        self.setWindowIcon(QtGui.QIcon("A.png"))# A icon

    def closeRoutine(self):
        self.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #set style
    style = """
        QPushButton{
            color: #ffffff;
            background: #8f8f8f;
            border: 3px #000000 solid;
            padding: 5px 10px;
            border-radius: 2px;
            font-weight: plain;
            font-size: 9pt;
            outline: none;
        }
        QPushButton:hover{
            border: 3px #000000 solid;
            background: #80aaff;
        }
    """
    ui = PopupWidget()
    ui.show()
    sys.exit(app.exec_())
