# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunnerTab(object):
    def setupUi(self, RunnerTab):
        RunnerTab.setObjectName("MainWindow")
        RunnerTab.resize(558, 600)
        RunnerTab.setDockNestingEnabled(True)
        self.runner_tab = QtWidgets.QWidget()
        self.runner_tab.setAccessibleName("")
        self.runner_tab.setObjectName("runner_tab")
        self.script_menu = QtWidgets.QComboBox(self.runner_tab)
        self.script_menu.setGeometry(QtCore.QRect(0, 0, 361, 22))
        self.script_menu.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.script_menu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.script_menu.setAcceptDrops(True)
        self.script_menu.setEditable(True)
        self.script_menu.setObjectName("script_menu")
        self.script_menu.addItem("")
        self.script_menu.addItem("")
        self.script_menu.addItem("")
        self.script_display = QtWidgets.QGraphicsView(self.runner_tab)
        self.script_display.setGeometry(QtCore.QRect(0, 30, 361, 491))
        self.script_display.setObjectName("script_display")
        self.run_button = QtWidgets.QPushButton(self.runner_tab)
        self.run_button.setGeometry(QtCore.QRect(370, 480, 151, 41))
        self.run_button.setObjectName("run_button")
        self.script_progress_terminal = QtWidgets.QGraphicsView(self.runner_tab)
        self.script_progress_terminal.setGeometry(QtCore.QRect(370, 30, 151, 411))
        self.script_progress_terminal.setObjectName("script_progress_terminal")
        self.script_progress_bar = QtWidgets.QProgressBar(self.runner_tab)
        self.script_progress_bar.setGeometry(QtCore.QRect(370, 0, 161, 20))
        self.script_progress_bar.setProperty("value", 24)
        self.script_progress_bar.setObjectName("script_progress_bar")
        self.script_timeout = QtWidgets.QSpinBox(self.runner_tab)
        self.script_timeout.setGeometry(QtCore.QRect(370, 450, 151, 22))
        self.script_timeout.setMinimum(1)
        self.script_timeout.setObjectName("script_timeout")
        self.tabWidget.addTab(self.runner_tab, "")
        
        self.retranslateUi(RunnerTab)
        RunnerTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(RunnerTab)

    def retranslateUi(self, RunnerTab):
        _translate = QtCore.QCoreApplication.translate
        RunnerTab.setWindowTitle(_translate("RunnerTab", "Runner"))
        self.script_menu.setCurrentText(_translate("RunnerTab", "Script1"))
        self.script_menu.setItemText(0, _translate("RunnerTab", "Script1"))
        self.script_menu.setItemText(1, _translate("RunnerTab", "Script2"))
        self.script_menu.setItemText(2, _translate("RunnerTab", "Script3"))
        self.run_button.setText(_translate("RunnerTab", "Run"))
        RunnerTab.setTabText(RunnerTab.indexOf(self.Runner), _translate("RunnerTab", "Runner"))

